Repository lissteron/loghole, pull requests merged in 2020-07, with the labels that each got.

#6 Feature: dashboard db init
  dashboard/backend/cmd/backend/main.go
  dashboard/backend/pkg/clickhouseclient/client.go
  dashboard/docker-compose-dev.yaml
  dashboard/scripts/go.mod
  dashboard/scripts/go.sum
  dashboard/scripts/populate_db/main.go
Labels: enhancement

#15 fix build
  dashboard/frontend/package.json
  dashboard/frontend/src/components/DateTime.vue
  dashboard/frontend/src/components/TagInput.vue
  dashboard/frontend/src/components/messages/Message.vue
  dashboard/frontend/src/components/messages/MessagesTable.vue
  dashboard/frontend/src/main.ts
  dashboard/frontend/src/types/view.ts
  dashboard/frontend/src/views/logs/View.vue
  dashboard/frontend/yarn.lock
Labels: bug

#16 Feature: backend update
  collector/cmd/collector/main.go
  collector/internal/app/controllers/http/handlers/middleware_auth.go
  dashboard/backend/cmd/backend/main.go
  dashboard/backend/internal/app/codes/codes.go
  dashboard/backend/internal/app/http/handlers/middleware_compress.go
  dashboard/backend/internal/app/http/request/req_entry_list.go
  dashboard/scripts/go.mod
  dashboard/scripts/go.sum
  dashboard/scripts/populate_db/main.go
  docker-compose-dev.yaml
Labels: bug, enhancement

#20 Hotfix/backen
  clickhouse-db/Makefile
  clickhouse-db/init.sql
  collector/Makefile
  collector/internal/app/domain/entry_test.go
  dashboard/Makefile
  dashboard/backend/cmd/dashboard/main.go
  docker-compose-alpha.yaml
Labels: bug

#21 Feature/backend/update
  README.md
  collector/cmd/collector/main.go
  collector/config/config.go
  collector/pkg/clickhouseclient/client.go
  collector/pkg/log/log.go
  collector/pkg/server/http.go
  dashboard/backend/cmd/dashboard/main.go
  dashboard/backend/config/config.go
  dashboard/backend/go.sum
  dashboard/backend/pkg/clickhouseclient/client.go
  dashboard/backend/pkg/log/log.go
  dashboard/backend/pkg/server/http.go
  docker-compose-alpha.yaml
  docker-compose-dev.yaml
Labels: enhancement

#22 add scroll
  dashboard/frontend/src/views/logs/View.vue
Labels: enhancement

#23 Feature/remote ip
  .gitignore
  README.md
  clickhouse-db/init.sql
  collector/cmd/collector/main.go
  collector/docker/default/Dockerfile
  collector/internal/app/controllers/http/handlers/handlers_entry.go
  collector/internal/app/controllers/http/handlers/middleware_remote_ip.go
  collector/internal/app/domain/entry.go
  collector/internal/app/repositories/clickhouse/repository.go
  collector/internal/app/services/entry/service.go
  collector/pkg/clickhouseclient/client.go
  dashboard/backend/internal/app/domain/entry.go
  dashboard/backend/internal/app/repositories/clickhouse/methods_entry.go
  dashboard/backend/internal/app/repositories/clickhouse/models/entry.go
  dashboard/backend/pkg/clickhouseclient/client.go
  dashboard/docker/default/Dockerfile
Labels: enhancement
